### ISSUE TITLE
Reference original project.

### ISSUE THREAD

**Issue by LukasMarckmiller** [Pushkar1853/nanoGPT#1]
While it is not a license issue, you take credit for someone [else's](https://github.com/karpathy/nanoGPT) efforts by not forking but cloning and republishing another users code. Besides that it's also a bad practice, because changes and fixes to the original repository can't be incooperated easily. Also it creates multiple not linked and not synchronzied copies of the same code.
I did not take a look on your other repos, but please don't just copy and present other peoples code as your own.

**Comment by Pushkar1853** [comment]
### Clarification Regarding Code Usage
I appreciate your concern and feedback regarding the recent code use from another user's repository. I want to address your points and clarify my intentions behind the actions you mentioned.

First and foremost, I want to ensure you know that my actions were not driven by any intention to claim credit for someone else's efforts. It was all a practice for reimplementing the codes from the lectures I wholeheartedly followed, and I wanted to continue that practice by posting codes on my GitHub as a resource for my future use. I have even added Jupyter notebooks which were part of the Zero to Hero ML Course on Youtube and probably absent in the main repo.

I acknowledge your point about forking versus cloning and republishing code. I understand that forking is recommended as it maintains the connection between the original and the forked repository. I'm very sorry for any confusion or concern my previous actions may have caused. So, I have mentioned the sources in the reference section in the readme.

Thank you for taking the time to share your thoughts.
Best Regards,
Pushkar

**Comment by LukasMarckmiller** [comment]
Thank you for the feedback and for including a reference. I understand your motivation and hope I was not to rude. 
Happy coding :)
